export const CIDADES = [
  { id: 1, nome: "São Paulo", uf: "SP" },
  { id: 2, nome: "Rio de Janeiro", uf: "RJ" },
  { id: 3, nome: "Salvador", uf: "BA" },
  { id: 4, nome: "Fortaleza", uf: "CE" },
  { id: 5, nome: "Belo Horizonte", uf: "MG" },
  { id: 6, nome: "Brasília", uf: "DF" },
  { id: 7, nome: "Curitiba", uf: "PR" },
  { id: 8, nome: "Manaus", uf: "AM" },
  { id: 9, nome: "Recife", uf: "PE" },
  { id: 10, nome: "Porto Alegre", uf: "RS" },
  { id: 11, nome: "Guarulhos", uf: "SP" },
  { id: 12, nome: "Campinas", uf: "SP" },
  { id: 13, nome: "São Gonçalo", uf: "RJ" },
  { id: 14, nome: "Belém", uf: "PA" },
  { id: 15, nome: "Duque de Caxias", uf: "RJ" },
  { id: 16, nome: "Nova Iguaçu", uf: "RJ" },
  { id: 17, nome: "Maceió", uf: "AL" },
  { id: 18, nome: "São Bernardo do Campo", uf: "SP" },
  { id: 19, nome: "Teresina", uf: "PI" },
  { id: 20, nome: "Porto Velho", uf: "RO" },
  { id: 21, nome: "Natal", uf: "RN" },
  { id: 22, nome: "Campo Grande", uf: "MS" },
  { id: 23, nome: "São José", uf: "SC" },
  { id: 24, nome: "Jaboatão dos Guararapes", uf: "PE" },
  { id: 25, nome: "Osasco", uf: "SP" },
  { id: 26, nome: "Santo André", uf: "SP" },
  { id: 27, nome: "João Pessoa", uf: "PB" },
  { id: 28, nome: "Ribeirão Preto", uf: "SP" },
  { id: 29, nome: "Sorocaba", uf: "SP" },
  { id: 30, nome: "Belford Roxo", uf: "RJ" },
  { id: 31, nome: "São José dos Campos", uf: "SP" },
  { id: 32, nome: "Cuiabá", uf: "MT" },
  { id: 33, nome: "Aracaju", uf: "SE" },
  { id: 34, nome: "Diadema", uf: "SP" },
  { id: 35, nome: "Feira de Santana", uf: "BA" },
  { id: 36, nome: "Vitória", uf: "ES" },
  { id: 37, nome: "Várzea Grande", uf: "MT" },
  { id: 38, nome: "Carapicuíba", uf: "SP" },
  { id: 39, nome: "Juiz de Fora", uf: "MG" },
  { id: 40, nome: "Londrina", uf: "PR" },
  { id: 41, nome: "Mauá", uf: "SP" },
  { id: 42, nome: "Bauru", uf: "SP" },
  { id: 43, nome: "São Vicente", uf: "SP" },
  { id: 44, nome: "Ipatinga", uf: "MG" },
  { id: 45, nome: "Campina Grande", uf: "PB" },
  { id: 46, nome: "Ananindeua", uf: "PA" },
  { id: 47, nome: "Macapá", uf: "AP" },
  { id: 48, nome: "Lages", uf: "SC" },
  { id: 49, nome: "Caxias do Sul", uf: "RS" },
  { id: 50, nome: "Uberlândia", uf: "MG" }
];
